#!/bin/bash
sysicondir="/usr/share/pixmaps /usr/share/icons /usr/local/share/pixmaps /usr/local/share/icons"
usricondir="$HOME/icons"
menuicon="22x22"
menuicondir="$HOME/.fvwm/images/menu/22x22"
com="${2##*/}"
if ! [ -s /tmp/updatemenu ]
then
	find $sysicondir $usricondir -path "*16x16" -prune -o -type f -iname "*.*" -print > /tmp/updatemenu
fi

if [ "$1" == "" ]
then
	icon=$com
else
	icon="${1##*/}"
	icon="${icon%.*}"
fi
if ! [ -f "$menuicondir/$icon.png" ] 
then
	if [ -f "$1" ]
	then
		convert "$1" -resize 22x22 "$menuicondir/$icon.png"
	else
		file="`grep -F "${icon}." /tmp/updatemenu`"
		if [ "$file" == "" ]
		then
			[ "$com" != folder ] && echo -n %"$menuicon/unknown.png"% || echo -n %"$menuicon/folder.png"%
			exit
		fi
		file="${file%%
*}"
		convert "$file" -resize 22x22 "$menuicondir/$icon.png"
	fi
fi
echo -n %"$menuicon/$icon.png"%
